name: Build
on: [push, pull_request]
jobs:
  build:
    strategy:
      matrix:
        java: [21-jdk]
    runs-on: ubuntu-24.04
    container:
      image: eclipse-temurin:${{ matrix.java }}
      options: --user root
    steps:
      - uses: actions/checkout@v4
      - uses: gradle/wrapper-validation-action@v1
      - run: ./gradlew build --stacktrace --warning-mode fail
